### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by erwanor** [fhajji/sodium-wrapper#2]
Hi @fhajji, neat work.

Do you plan on maintaining it or is the disclaimer in the README still applies?

**Comment by fhajji** [comment]
Hello @aaronwinter, thanks.

Yes, I intend to. I was sidetracked by another project, but I'm still here.

**Comment by fhajji** [comment]
Continuing with the project now. The disclaimer still applies though. Sorry for the long delay.
