### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by patlecat** [fhajji/sodium-wrapper#3]
Can you please update and stabilize it? We really need a C++ interface.

**Comment by fhajji** [comment]
Okay, I'll take a look soon. Thanks.

**Comment by fhajji** [comment]
Hello,

as you can see, sodium-wrapper now compiles on Windows too. There are still some issues to take care of like some failing unit tests. After that, may I suggest the current roadmap in README.md?

Of course, any help would speed up development a lot.
