### ISSUE TITLE
Is this library still maintained?

### ISSUE THREAD

**Issue by samuel-lucas6** [fhajji/sodium-wrapper#4]
Hi @fhajji, I'm currently trying to tidy up the bindings linked on the libsodium website. If this library is still maintained, then please let me know; otherwise, the link to this library will [likely](https://github.com/jedisct1/libsodium-doc/pull/156#issuecomment-1067834246) be removed from the [bindings](https://doc.libsodium.org/bindings_for_other_languages) page to help users find up to date and maintained bindings.

**Comment by fhajji** [comment]
Hi @samuel-lucas6, I'm currently super busy, but I do plan to update sodium-wrapper in a few months. In the mean time, I think it is best to remove the link so people don't use an outdated library.

**Comment by samuel-lucas6** [comment]
Thanks for getting back to me; I'll make a note of that.

**Comment by samuel-lucas6** [comment]
I'm going to close this to help keep track of who hasn't replied yet. Please wait until the PR has gone through if you want to reopen it :)
